export const ASYNC_OPERATION_STARTED = 'ASYNC_OPERATION_STARTED';
export const ASYNC_OPERATION_FINISHED = 'ASYNC_OPERATION_FINISHED';
export const ASYNC_OPERATION_FAILED = 'ASYNC_OPERATION_FAILED';
export const ASYNC_OPERATION_INIT = 'ASYNC_OPERATION_INIT';
